language: java

env:
  global:
    - secure: JFM0oS3ME5ScymrVmnxWr+ubTp1lev9jYo0bDM5XDY4lBp5/OJtkuJEsE2aZn8MH2IF4umV4u3mwSZibewjXgb9MsIHyVcQp4v5uYmelt0UO4drj5rx0FcZkPBXOZ8/61/R+/oSdPWTiqoV429aLq2YoYDoVgh4hBKRgjBy9dNfftAS0Ykqpy4au1/4GUzFo6ryJYI95HgcXwOMDzw2pOstHRl1UcWVE/xgaV2Z2br/qjLSjrU0Zc+A8H3CFNDYMocoraViPQhfyPv05QyuDWLJmUGjfGvC8EzJgCibSf94MxNBMR9GQrBqa0oi7h7kB0oD0vIx1R/13vKD6Ors9DKVvdZiEWGrupolI7J8ulbg+yZoeg6sryuu9fRqj5v+nY6wOFMYiT6/DufzFX4PgrzBOk8YeUUqW6doMVmyMDGOY88ZmCusEtvP1MRtPMA4G0ELtgWKOdvcD36jVWD47weM2pC3wfic45/QKuu9wz7iKDMTK/Z3KCM6OyyEjLoLy7ztOZsX+v6qVwjaEy8cgjZh76/MmXbB+EGdReRetfFy+N3Vxls+IsDBo8iAtX4jnaSow/04v2lv5r/+0zSS6aaJJMnaBmESj2UrE97JEcBZ2sDoShhLKxECiDdY/KBulisjUNQHcSW1W5y4rv17B3RVB8PIFbNwoVD6SCLlTPGY=
    - secure: dIgH4RuM5TmhvYvqctT6asyc+SY9FbHVbOtZgmfkj9jCnwJFWu4e0XVc7hMscKUp5r/pyzih+r8hy6+qPSQlwLrKMemLwKI2GmeUDzw/xclEBCr27jHl8YA3S7NDG+Q/eSDzAEuD39yt57tTv4RyVkcpg+LG9g3D3KVyMpvkxAmEeKGwGdlSMxYFuXchWbx2ft0glEJQcNhKMOT6nfJJwhxozjHO822zAHAgcJvJzDOtlphRkkDXwt3ycrGyGM70ov7AKMwy6O4otEPb6h10GTFuPyh3s7ypSOGNhnmOnoisJtJ8c59Q+vMvCI0Nqda0fdVjxpuepfUb+jVHQRmPH0dzqS9TEF408oPtnqrWpZZO1H/1AobucNJdsKqJU3uq6U/iYpsCUOzNXB40QVFzS8nD/alWioVNzqZyi+i4PVh56dGcYSgDyvHXmMvyqj1RXKcaAgefVu3ZDlrsZF3Y8yCTBbiBCPFsFIpP8jUkkwbvI9CMLugJd4IBA7d1YRxPdDN7uml5S1C8CLDhUXhONaLgScIhp8eV0QUm4hRgkntH6RlB0wnv/g7bGO8lL7dMwrFO/mYDec6+qJKKjDFPuXiBMgnRxk5mzosbGjj0bnmSYsXNiV90aw3LS+ZCdxZ7eAKW7Mg9cKct5o/391ndSQ6xDFwqrnEU0Ke4iKkm4i4=
    - secure: m6aQ/DUdYqz26iV8+tya4q3jkXXHznsN8HRvnoVzBu85rDatKex5nyCW38mmkoSdyzk6CGK3cxk6le9mV4Y6CTTl0zJuf5BEXjeSzBpdBIpTKGLjVsNMi3UT3+DixZs7VMxQvByJoa63ZVCmzBkKenl+vkmRaI8lr1Q4pc1JK1wpkaH0gXRxonN1im3qH4rXFcG60btYZdZGIHczbU27h3TN8IfImkwnf1BRtuTVGth2fyAQgyzWQZcuOM5thwXAWDERtWHa9zTS5xbF0LAJO6U8UyTc7JDXyNxmot2aR2sN35J3UhCS8WU93eReowSlg1a8ZrVZ4fyDc2T/v4L8jPO1yKeCADj85DLPqnh+DXa6Mi5uGyCFtB7Kg84EoD96VWcxzDV4JGil9/h5OJkBe7zcdFpRAkdpih1BpOW62taVl9ZOKTgL8vpU8XXpFKdkXLI1XP30jVIRICdvl8wTfSp+tYEbAt0HlSeymmgw5ibvEcvHOayXSdEDSODKid/ov9gFvkaeKnGyuanJX4BnqgMKkFWA7rv9Ff7qku+woysDyZ+fPWKXiDoLS46WJELrGqlycEFBRivtz//4BjgYu48UhnM1w2XrzIaaC9WEtrHB/aKrjuvTMsYdcAFP3s52kdKF6VXjf0vDNx1YseAVgkMhfsw+jEz9h6NRYlrX88o=

# Taken from https://github.com/Codearte/gradle-nexus-staging-plugin/blob/master/.travis.yml
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -fr $HOME/.gradle/caches/*/scripts/
  - rm -fr $HOME/.gradle/caches/*/scripts-remapped/
  - rm -fr $HOME/.gradle/caches/*/fileHashes/
  - rm -f $HOME/.gradle/caches/*/fileContent/*.lock
  - rm -f $HOME/.gradle/caches/*/javaCompile/*.lock
  - rm -f $HOME/.gradle/caches/*/executionHistory/*.lock
  - rm -f $HOME/.gradle/caches/*/generated-gradle-jars/*.lock
  - rm -f $HOME/.gradle/caches/transforms-1/transforms-1.lock
  - rm -f $HOME/.gradle/caches/journal-1/file-access.bin
  - rm -f $HOME/.gradle/caches/journal-1/*.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jobs:
  include:
    - stage: test
      jdk: openjdk8
    - stage: test
      jdk: openjdk11
    - stage: test
      jdk: openjdk12

    - stage: deploy
      if: repo = "bozaro/git-lfs-java" and type != "pull_request" and (branch = "master" or tag is present)
      jdk: openjdk8 # Deploy releases using oldest supported jdk
      install: true
      script:
        - openssl aes-256-cbc -K $encrypted_8e5c960335c9_key -iv $encrypted_8e5c960335c9_iv -in secring.gpg.enc -out secring.gpg -d
        - ./gradlew --info publish closeAndReleaseRepository
